### ISSUE TITLE
[Firmware Request]: BRAND - ZW NUMBER - PRODUCT NUMBER

### ISSUE THREAD

**Issue by gupta-ash** [jascoproducts/firmware#103]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW1001

### Product Number

12721

**Comment by jasondefuria** [comment]
Read the docs @gupta-ash. This has been brought up and it is not able to be updated.

**Comment by jascoproducts** [comment]
This is covered under many previous closed issues as well as in our Readme documentation. This product was manufactured before the Z-Wave Alliance had created a standardized OTA method. Any products (for any manufacturer) marked with a simple Z-Wave Logo cannot be updated. Only products marked with the Z-Wave Plus logo can be updated.
