### ISSUE TITLE
[Firmware Request]: JASCO- ZW4101 - Plug-in 2-outlet Switch

### ISSUE THREAD

**Issue by dbakez** [jascoproducts/firmware#108]
### What brand is the request for?

Jasco

### ZW Number

ZW4101

### Product Number

zw4101

**Comment by jascoproducts** [comment]
@dbakez Hey, thanks for the request. The ZW4101 line is actually composed of legacy 300 series Z-Wave devices, and the technology at the time of 300S did not support OTA updates the way that Z-Wave Plus (500 series and up) devices do today. Those units can't be updated.
