### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by Skates1616** [jascoproducts/firmware#112]
I am using Z-Wave PC Controller and when I click update for a ZW4005 switch, it never starts, I only see this message and it never completes:

![image](https://user-images.githubusercontent.com/23196661/224790576-e4f655a7-9f5a-4b2a-bab3-94df00d62cdb.png)

It completes with the following message:

![image](https://user-images.githubusercontent.com/23196661/224791386-685e9774-e930-4ff4-a44e-64e9c181fc59.png)

Any tricks I should be aware of to get this switch updated?

**Comment by jascoproducts** [comment]
Try these 2 options, let us know if any work:
Option 1: Remove and re-add the device and try again.
Option 2: Try using 39348's firmware.

**Comment by Skates1616** [comment]
No go, I tried both options and am still receiving the same error.  I tried updating a Fan Switch (ZW4002) too and am receiving the same error.

I know updating works as I just updated a Inovelli switch as a test with the two firmware, it updated with no issue.

Any thoughts on what may be preventing the devices from updating?

**Comment by jascoproducts** [comment]
@Skates1616 Did you ever manage to get this updated? If not, and you'd still be up to troubleshoot again, can you send us a screenshot of a Manufacturer_Specific_Get as shown below:

![image](https://github.com/jascoproducts/firmware/assets/106697048/f3521b62-ba43-47f0-af59-69ac030dd237)
