### ISSUE TITLE
[Bug Report]: GE - ZB4001 - 45856GE

### ISSUE THREAD

**Issue by andrejpavlovic** [jascoproducts/firmware#115]
### What brand is the bug report for?

Enbrighten-GE

### ZW Number

ZB4001

### Product Number

45856GE

### FW Version

original

### Bug Report Details

I installed two ZB4001 switches recently. I noticed that there is a half-second delay from when the rocker is pressed to when the light turns on. There is no such delay if I turn the switch on/off from the hub.

I understand that some smart switches purposely add this delay in order to detect single/double/triple taps, or press-and-hold input, but this switch doesn't support any of those features, so why is there still a delay when toggling the switch physically?

Is there any way to configure that via a Zigbee hub?

### How To Reproduce

1. Mount GE Zigbee Smart Switch In-Wall in place of an existing switch.
2. Press and release the top of the rocker.

Result:
It takes exactly 500ms from pressing the switch to the light turning on.

Expected:
Ideally there should be almost no delay.

**Comment by jascoproducts** [comment]
Thanks for reaching out. You are correct that switches will need this for single/double/triple taps. Ultimately its added for any multiple button press function. All of our Zigbee devices can adjust the LED light on the front panel by pressing 3 up 1 down quickly.
