### ISSUE TITLE
[Bug Report]: Enbrighten-GE - ZW4009 - 14293 - 5.54

### ISSUE THREAD

**Issue by pcburcham** [jascoproducts/firmware#116]
### What brand is the bug report for?

Enbrighten-GE

### ZW Number

4009

### Product Number

14293

### FW Version

5.54

### Bug Report Details

When tapping toggle up/down more than once for scene control, the load the switch is connected to is controlled also. In other words, both taps (single **and** double/triple) are registered and the controller receives both commands instead of the intended double/triple tap action (only).  

**I reverted the switch firmware to 5.53 and the switch scene taps are operating as expected.**

### How To Reproduce

Double or triple-tap switch (up or down) for scene control. The primary load (single-tap) will turn on or off as well, instead of only controlling the intended device or scene. 

As mentioned, reverting to firmware 5.53 corrects the issue.

**Comment by jascoproducts** [comment]
@pcburcham In moving forward from 5.53, we did a cost-benefit analysis on whether or not to keep the relay delay. For all those who enjoyed the function of the multi-tap, we had many more that complained about the delay, so we decided to remove it from future versions.

There is no difference between 5.54 and 5.53 other than the delay removal. Please switch to 5.53 if you desire the multi-tap functionality.
