### ISSUE TITLE
[Firmware Request]: Enbrighten-GE In-Wall Paddle Dimmer, 300S

### ISSUE THREAD

**Issue by jamenlang** [jascoproducts/firmware#121]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW3005

### Product Number

screenshot

**Comment by jamenlang** [comment]
![image](https://github.com/jascoproducts/firmware/assets/6394127/f5023d34-746e-4fb5-9672-c9d72fc9566f)

**Comment by jascoproducts** [comment]
Closing alongside #120 as there is no additional firmware available for non-upgradable 300S devices.
