### ISSUE TITLE
[Firmware Request]: GE - ZW4003 - 14293

### ISSUE THREAD

**Issue by bens545** [jascoproducts/firmware#18]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4003

### Product Number

14293

**Comment by AllBaconAndEggs** [comment]
Also requesting newer firmware for this model if available

**Comment by jascoproducts** [comment]
@bens545 @AllBaconAndEggs Currently this is not on this weeks release list, We will add to the following weeks release.

**Comment by jascoproducts** [comment]
@bens545 @AllBaconAndEggs live with latest major update! See [here.](https://github.com/jascoproducts/firmware/tree/main/zwave/Enbrighten-GE/ZW4009/14293%20-%20In-Wall%20Smart%20Toggle%20Switch%20(Lt.%20Alm))
