### ISSUE TITLE
Your Revision History files should probably be csv files

### ISSUE THREAD

**Issue by NatoNathan** [jascoproducts/firmware#23]
You are using Excel files for your Revision history, these should probably be csv files because GitHub can render them as a table. This will become beneficial as you continue to add updates.

**Comment by crxporter** [comment]
I fully agree with your comment - I downloaded and opened several of the csv files yesterday and was slightly annoyed.

Then I noticed that the revision history is *also* available in the "readme" file right next to each downloadable file. Would be awesome if both were file types that play nice with GH.

Example:
![image](https://user-images.githubusercontent.com/38265886/173196406-2251bb79-c93c-4e31-bb5d-1640d4c65909.png)

**Comment by niemyjski** [comment]
Also, I was looking over the notes for the switches I have that you've provided. The release notes say something like initial release, but my firmware is much older. Would be nice to see a change log for all versions of the firmware.
