### ISSUE TITLE
[Firmware Request]: Enbrighten-GE - ZW4007 - 14285

### ISSUE THREAD

**Issue by xTerminatioNx** [jascoproducts/firmware#3]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4007

### Product Number

14285

**Comment by jascoproducts** [comment]
@xTerminatioNx Thanks for your request. the 14285 is not slated for this fridays release, but we will be adding it to the following weeks release.

**Comment by jascoproducts** [comment]
@xTerminatioNx Posted with most recent major update! Find the firmware .zip [here.](https://github.com/jascoproducts/firmware/tree/main/zwave/Enbrighten-GE/ZW4007/14285%20-%20Direct%20Wire%2040A%20Outdoor%20Smart%20Switch/5.55)
