### ISSUE TITLE
[Firmware Request]: <Enbrighten-GE> - <ZW3004> - <12729> 

### ISSUE THREAD

**Issue by kernelpanic85** [jascoproducts/firmware#31]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW3004

### Product Number

12729

**Comment by jascoproducts** [comment]
@kernelpanic85 @AllBaconAndEggs We appreciate the requests. Unfortunately this is a Z-Wave Classic product and cannot be updated via OTA.
