### ISSUE TITLE
[Firmware Request]: <Enbrighten-GE> - <ZW1001> - <?> 

### ISSUE THREAD

**Issue by kernelpanic85** [jascoproducts/firmware#33]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW1001

### Product Number

?

**Comment by jascoproducts** [comment]
@kernelpanic85 Thank you again for your request. Unfortunately, all models of the ZW1001 were Z-Wave Classic products that cannot be updated via OTA.

**Comment by OmgImAlexis** [comment]
@jascoproducts so why not release the firmware for those that want to flash via other methods..?
