### ISSUE TITLE
[Firmware Request]: Enbrighten-GE - ZW4003 - 14292 

### ISSUE THREAD

**Issue by AllBaconAndEggs** [jascoproducts/firmware#36]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4003

### Product Number

14292

**Comment by jascoproducts** [comment]
@AllBaconAndEggs Appreciate the continued interest. This model is also slated for this Friday's release.

**Comment by jascoproducts** [comment]
Added with this week's Friday release.
