### ISSUE TITLE
[Firmware Request]: Jasco - ZW4008 - 46562

### ISSUE THREAD

**Issue by tagno25** [jascoproducts/firmware#42]
### What brand is the request for?

Jasco

### ZW Number

ZW4008

### Product Number

46562

**Comment by jascoproducts** [comment]
Released in latest major update. [Enjoy!](https://github.com/jascoproducts/firmware/tree/main/zwave/Jasco/ZW4008/46562%20-%20In-Wall%20Smart%20Paddle%20Switch)
