### ISSUE TITLE
[Firmware Request]: GE - ZW4003 - 12727

### ISSUE THREAD

**Issue by onlize** [jascoproducts/firmware#45]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4003

### Product Number

12727

**Comment by jascoproducts** [comment]
@onlize Thank you for your interest, however this version is a 300 Series Z-Wave classic device and it is unable to be updated via OTA.

**Comment by onlize** [comment]
Hi, Is there any way to update the switch not via OTA?

Thank you.
