### ISSUE TITLE
[Firmware Request]: Enbrighten-GE - ZW4008 - 39348 / 54890 / 54891

### ISSUE THREAD

**Issue by MattWeiler** [jascoproducts/firmware#46]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4008

### Product Number

39348 / 54890 / 54891

**Comment by jascoproducts** [comment]
@MattWeiler Thanks for your question additional elaboration. The brand for that product is actually UltraPro. The available firmware files are already listed under the UltraPro folder. Apart of this project is working to clean up brands, models and descriptions that are pulled in by Home Assistant and other Open Source platforms. We will be updating the Firmware Request to better explain where to look specifically as well as where to get the information we need in the coming days to better help with identifying the products. Thank you again for your request, we really do appreciate it, as it is helping us identifying areas where we can improve.
