### ISSUE TITLE
[Firmware Request]: <Honeywell> - <ZW4002> - <39358> 

### ISSUE THREAD

**Issue by nholben** [jascoproducts/firmware#47]
### What brand is the request for?

Honeywell

### ZW Number

ZW4002

### Product Number

39358

**Comment by jascoproducts** [comment]
@nholben Live as of last major update. [Here you go!](https://github.com/jascoproducts/firmware/tree/main/zwave/Honeywell/ZW4002/39358%20-%20In-Wall%20Smart%20Fan%20Speed%20Control)
