### ISSUE TITLE
Enable GitHub Discussions 

### ISSUE THREAD

**Issue by NatoNathan** [jascoproducts/firmware#49]
Another suggestion enable GitHub Discussions on this repo, this will allow users to ask questions related to your firmware and products without cluttering the repos issues. That way issues should only have bug reports and firmware requests, and anyone looking for help can easily find it or ask in the Discussions.

**Comment by jascoproducts** [comment]
@NatoNathan We are working through each request and updating our releases, but I saw this and wanted to respond immediately -Hope no one gets offended I skipped to the end 

You are spot on with what we are looking to implement. We will be setting up for General Questions to help anyone with questions on the information they find here on GitHub, and feature requests along with others. We will be building this out and trying to get a better cadence with everyone. Keep the suggestions coming. We have gotten great contribution so far and it can only help make this project better.
