### ISSUE TITLE
Devices with hardware not matching faceplate: 12724 / ZW3003 (ZW3005)

### ISSUE THREAD

**Issue by EdenNelson** [jascoproducts/firmware#57]
I have multiple devices with mismatched hardware faceplates vs reported hardware via firmware.
Marked as  GE - ZW3005 - Date Code 1615
Firmware reports as 12724 / ZW3003

**Comment by jascoproducts** [comment]
If you can provide us with images of the front of the product without the wallplate and screenshots of what reporting data that you are seeing, the more information the better including what system you are using we can try to help where the discrepancy might be.

**Comment by jascoproducts** [comment]
@EdenNelson Wanted to follow up on this. We reviewed further with the Z-Wave JS entries and we have found a "12724 / ZW3003". When we reviewed the the Z-Wave Manufacturer Specific data for the entry and what our Dimmer reports, it is specifically for "12724 / ZW3005" This model is a Z-Wave Classic 300 series product that cannot be updated via OTA. The reporting data from the dimmer is correct and the marking on your dimmer is correct as well, it is just an error on the Z-Wave JS entry.

We have added this to correct the entry on Z-Wave JS when we suggest the rest of the updates to clean up brands, descriptions, etc. Let us know if you need further assistance.

**Comment by EdenNelson** [comment]
Please see attached images. These devices clearly marked as ZW3005 but the internals are ZW3003.

Your identification documentation need updated to reflect that ZW3003 are marked as ZW3005.

![62D6EE77-538C-4545-AC39-B6AE0F6F8886](https://user-images.githubusercontent.com/16840996/177013245-7f66947e-097a-4de0-a5c3-13294dd77f78.jpeg)
![25C70C25-D532-42BD-8380-92D0F38FF206](https://user-images.githubusercontent.com/16840996/177013247-43ca3979-1d93-4f07-8434-5d42b9a6bab6.jpeg)

**Comment by jascoproducts** [comment]
[This specific device has been fixed.](https://devices.zwave-js.io/?jumpTo=0x0063:0x4944:0x3031:0.0) Thanks for reporting. Soon we will be rolling out a huge device info update for everything else - stay tuned.

**Comment by jascoproducts** [comment]
Updated title to reflect Z-Wave JS database fix.
