### ISSUE TITLE
[Firmware Request]: Enbrighten-GE - ZW1001 - PRODUCT NUMBER N/A

### ISSUE THREAD

**Issue by paulsievers** [jascoproducts/firmware#65]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW1001

### Product Number

N/A

**Comment by jascoproducts** [comment]
@paulsievers that would indeed be 12721 and ZW1001; you have it correctly identified. This is also a 300-series product ([Z-Wave, not Z-Wave Plus](https://github.com/jascoproducts/firmware#product-identification)) and thus cannot be updated with OTA.
