### ISSUE TITLE
[Firmware Request]: Jasco - ZW4006 - 26931

### ISSUE THREAD

**Issue by infamy** [jascoproducts/firmware#73]
### What brand is the request for?

Jasco

### ZW Number

ZW4006

### Product Number

26931

**Comment by jascoproducts** [comment]
@infamy Hey there, thanks for the request. Find 26931's firmware [here.](https://github.com/jascoproducts/firmware/tree/main/zwave/Enbrighten-GE/ZW4006/26931%20-%20In-Wall%20Smart%20Motion%20Switch)
