### ISSUE TITLE
[Firmware Request]: Enbrighten-GE- ZW4008DV - 43072

### ISSUE THREAD

**Issue by lcasale** [jascoproducts/firmware#74]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4008DV

### Product Number

43072

**Comment by lcasale** [comment]
Assuming the firmware for this switch is different from ZW4008-46201 (which is already posted). Thanks!

**Comment by jascoproducts** [comment]
@lcasale correct. Scheduled for next week's update! Thanks.

**Comment by lcasale** [comment]
Awesome thank you. Love that you guys are doing this!!

**Comment by jascoproducts** [comment]
@lcasale Just posted! Turns out there was only one release for this device so hopefully settles any doubts. Find it [here.](https://github.com/jascoproducts/firmware/tree/main/zwave/Enbrighten-GE/ZW4008DV/43072%20-%20In-Wall%20Smart%20Paddle%20Switch%20(120%2B277))
