### ISSUE TITLE
[Question]: Expose Light Sensor to ZWave? (ZW4006/26931)

### ISSUE THREAD

**Issue by randoogle** [jascoproducts/firmware#76]
I've installed several of these motion sensor light switches in my house, and there's a couple of instances where it would be nice if I could have access to the light levels from the light sensor for additional automatons. Is the light level sensor something that could be exposed to the ZWave interface?

**Comment by jascoproducts** [comment]
Thanks for the feedback. We have actually looked at that as a feature for a new hardware version of this product. This current hardware platform does not have a light sensor that can return specific light levels and therefore is not designed to expose the light sensor to Z-Wave.
