### ISSUE TITLE
[Firmware Request]: Jasco - ZW3008

### ISSUE THREAD

**Issue by jeffh0821** [jascoproducts/firmware#77]
### What brand is the request for?

Jasco

### ZW Number

ZW3008

### Product Number

NA. Identical to Enbrighten-GE ZW3008 - but fails firmware check if attempting to use Enbrighten-GE firmware
![PXL_20220713_000813544](https://user-images.githubusercontent.com/25091325/178746742-8c0624cd-6c62-4c82-b1c8-efcd03e2e370.jpg)
.

**Comment by jascoproducts** [comment]
@jeffh0821 correct, this is indeed a separate Jasco-branded device from the one with firmware currently uploaded. Sorry for any trouble with firmware install conflicts and having to pull the wall plate. We appreciate the ID pic though.

Thanks for the request too; this is the first and currently the only device on the list for this week. We will work on getting this uploaded and get back to you soon.

**Comment by jascoproducts** [comment]
@jeffh0821 [Here you go!](https://github.com/jascoproducts/firmware/tree/main/zwave/Jasco/ZW3008/26932%20-%20In-Wall%20Smart%20Motion%20Dimmer) Thanks for the request.
