### ISSUE TITLE
[Firmware Request]: BRAND - ZW NUMBER - PRODUCT NUMBER

### ISSUE THREAD

**Issue by ezeitoun** [jascoproducts/firmware#88]
### What brand is the request for?

Enbrighten-GE

### ZW Number

ZW4001

### Product Number

45609

**Comment by jascoproducts** [comment]
@ezeitoun Thanks for the request - this is actually a Z-Wave 300-series device which, due to limitations of the platform hardware itself, does not support firmware updates. Sorry about that.
