### ISSUE TITLE
[Bug Report]: Enbrighten-GE - ZW4203 - 14298 - Plug-in Outdoor Switch V2, 500S - 5.53

### ISSUE THREAD

**Issue by hecon5** [jascoproducts/firmware#92]
### What brand is the bug report for?

Enbrighten-GE

### ZW Number

ZW4203

### Product Number

14298 - Plug-in Outdoor Switch V2, 500S

### FW Version

5.53

### Bug Report Details

Firmware 5.53 appears to mislabel the firmware on the device, or does not update the device.

Current version of Firmware as shown by device: 5.52
Current version of Firmware listed on repo: 5.53.

After updating, firmware reported by device is still 5.52; this is true for several different controllers attempts to update firmware.

### How To Reproduce

Download firmware 5.53
Attempt to update firmware on device to 5.53. 

Device takes update, reports back firmware is still 5.52.

Multiple attempts to update have failed with multiple different controllers (HomeSeer Pi, Zooz S2700 Series, Aeotec) using multiple different front ends (HomeSeer, Home Assistant, SilliconLabs Zwave IDE).

**Comment by jascoproducts** [comment]
@hecon5 Thank you for catching this. This is a mistake on our end and the version number should indeed have been 5.52. Just fixed.
