### ISSUE TITLE
[Bug Report]: UltraPro - ZW3010- 39351 - VER 5.4 (printed on back)

### ISSUE THREAD

**Issue by rssalerno** [jascoproducts/firmware#97]
### What brand is the bug report for?

UltraPro

### ZW Number

ZW3010

### Product Number

39351

### FW Version

VER 5.4 (printed on back)

### Bug Report Details

Dimming speed when turning off switch locally is always slow regardless of the value of parameter 6.  
Dimming speed when turning on switch locally is always slow regardless of the value of parameter 6, except if parameter 32 is set to <99.  

Slow dim speed, especially when turning off, forces the user to wait for visual confirmation that the light is actually turning off (or wait for the light to slowly turn on) which is inconsistent with user expectations.

Need a way to adjust dimming speed that works in all circumstances.

### How To Reproduce

1) set parameter 6 to zero.
2) turn on switch with local paddle
3) light ramps on slowly
4) turn off switch with local paddle
5) light ramps off slowly

**Comment by jascoproducts** [comment]
This is a dimmer-bulb related performance issue. We try to account for ramping performance on as many bulbs as possible that are on the market at the time of developing the device, but this is always a moving target and the installed firmware always suits some bulbs better than others. We try to cover that spectrum as best we can to ensure adequate performance for as many users as possible.

We don't plan on releasing updated firmware for this device as we transition to a newer hardware platform. However, we understand your request and we will work to improve our ramping performance on newer devices as we develop firmware for them.
