### ISSUE TITLE
[Firmware Request]: Jaasco - ZW1001-WCS - 45605

### ISSUE THREAD

**Issue by dpeart** [jascoproducts/firmware#98]
### What brand is the request for?

Jasco

### ZW Number

 45605 / ZW1001-WCS

### Product Number

45605

**Comment by dpeart** [comment]
I have three of these, two have v 1.16 and one has v1.11 firmware.  I would like to upgrade the v1.11 outlet.

**Comment by jascoproducts** [comment]
Hi there. 45605 is actually a legacy 300 series Z-Wave device, and the technology at the time did not support OTA updates Z-Wave Plus devices do. This unit cannot be updated.

**Comment by dpeart** [comment]
Ok, that is disappointing as the v 1.16 allows the outlet to beam.  I was hoping to have them all beam.

thanks
